### ISSUE TITLE
Async Talks

### ISSUE THREAD

**Issue by SupahNoob** [rednafi/thinking-asyncio#2]
This is a great start! You might think to add these talks..

Dave Beazley's "Build your own Async"
https://youtu.be/Y4Gt3Xjd7G8
It's not necessarily specifically about asyncio, however the content very much underlies asyncio's architecture and inner workings.

Edge DB's channel
https://www.youtube.com/channel/UCRF82wX0EPwqvKMBwvB4fQg
There are only 3 videos at the time of writing this, but Łukasz and EdgeDB have plans for more videos which goes very in-depth on asyncio specifically.

Hope this helps!

**Comment by rednafi** [comment]
Hi thanks for the addition! All the talks look fun and updated. Could you please add them under the Talks section and send a PR? I'll merge. 🔥🔥
